### ISSUE TITLE
checkinstall keeps failing

### ISSUE THREAD

**Issue by Itai-Nelken** [giuliomoro/checkinstall#3]
I'm trying to package QEMU to a deb, but checkinstall keeps failing.

here is the terminal output:
```bash
pi@Twisterpi4-ultra-4gb:~/Documents/qemu $ sudo checkinstall

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.



*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ root@Twisterpi4-ultra-4gb ]
1 -  Summary: [ qemu ]
2 -  Name:    [ qemu ]
3 -  Version: [ 20210123 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ armhf ]
8 -  Source location: [ qemu ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ qemu ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue: 

Installing with make install...

========================= Installation results ===========================
changing dir to build for make "install"...
make[1]: Entering directory '/home/pi/Documents/qemu/build'
[1/176] Generating qemu-version.h with a custom command (wrapped by meson to capture output)
[2/34] Generating ar with a custom command
[3/34] Generating bepo with a custom command
[4/34] Generating cz with a custom command
[5/34] Generating da with a custom command
[6/34] Generating de with a custom command
[7/34] Generating de-ch with a custom command
[8/34] Generating en-gb with a custom command
[9/34] Generating en-us with a custom command
[10/34] Generating es with a custom command
[11/34] Generating et with a custom command
[12/34] Generating fi with a custom command
[13/34] Generating fo with a custom command
[14/34] Generating fr with a custom command
[15/34] Generating fr-be with a custom command
[16/34] Generating fr-ca with a custom command
[17/34] Generating fr-ch with a custom command
[18/34] Generating hr with a custom command
[19/34] Generating hu with a custom command
[20/34] Generating is with a custom command
[21/34] Generating it with a custom command
[22/34] Generating ja with a custom command
[23/34] Generating lt with a custom command
[24/34] Generating lv with a custom command
[25/34] Generating mk with a custom command
[26/34] Generating nl with a custom command
[27/34] Generating no with a custom command
[28/34] Generating pl with a custom command
[29/34] Generating pt with a custom command
[30/34] Generating pt-br with a custom command
[31/34] Generating ru with a custom command
[32/34] Generating th with a custom command
[33/34] Generating tr with a custom command
[33/34] Installing files.
Installing subdir /home/pi/Documents/qemu/qga/run to /usr/local/var/run
Installing trace/trace-events-all to /usr/local/share/qemu
Installing qemu-system-aarch64 to /usr/local/bin
Stripping target 'qemu-system-aarch64' using strip.
Installing qemu-system-alpha to /usr/local/bin
Stripping target 'qemu-system-alpha' using strip.
Installing qemu-system-arm to /usr/local/bin
Stripping target 'qemu-system-arm' using strip.
Installing qemu-system-avr to /usr/local/bin
Stripping target 'qemu-system-avr' using strip.
Installing qemu-system-cris to /usr/local/bin
Stripping target 'qemu-system-cris' using strip.
Installing qemu-system-hppa to /usr/local/bin
Stripping target 'qemu-system-hppa' using strip.
Installing qemu-system-i386 to /usr/local/bin
Stripping target 'qemu-system-i386' using strip.
Installing qemu-system-m68k to /usr/local/bin
Stripping target 'qemu-system-m68k' using strip.
Installing qemu-system-microblaze to /usr/local/bin
Stripping target 'qemu-system-microblaze' using strip.
Installing qemu-system-microblazeel to /usr/local/bin
Stripping target 'qemu-system-microblazeel' using strip.
Installing qemu-system-mips to /usr/local/bin
Stripping target 'qemu-system-mips' using strip.
Installing qemu-system-mips64 to /usr/local/bin
Stripping target 'qemu-system-mips64' using strip.
Installing qemu-system-mips64el to /usr/local/bin
Stripping target 'qemu-system-mips64el' using strip.
Installing qemu-system-mipsel to /usr/local/bin
Stripping target 'qemu-system-mipsel' using strip.
Installing qemu-system-moxie to /usr/local/bin
Stripping target 'qemu-system-moxie' using strip.
Installing qemu-system-nios2 to /usr/local/bin
Stripping target 'qemu-system-nios2' using strip.
Installing qemu-system-or1k to /usr/local/bin
Stripping target 'qemu-system-or1k' using strip.
Installing qemu-system-ppc to /usr/local/bin
Stripping target 'qemu-system-ppc' using strip.
Installing qemu-system-ppc64 to /usr/local/bin
Stripping target 'qemu-system-ppc64' using strip.
Installing qemu-system-riscv32 to /usr/local/bin
Stripping target 'qemu-system-riscv32' using strip.
Installing qemu-system-riscv64 to /usr/local/bin
Stripping target 'qemu-system-riscv64' using strip.
Installing qemu-system-rx to /usr/local/bin
Stripping target 'qemu-system-rx' using strip.
Installing qemu-system-s390x to /usr/local/bin
Stripping target 'qemu-system-s390x' using strip.
Installing qemu-system-sh4 to /usr/local/bin
Stripping target 'qemu-system-sh4' using strip.
Installing qemu-system-sh4eb to /usr/local/bin
Stripping target 'qemu-system-sh4eb' using strip.
Installing qemu-system-sparc to /usr/local/bin
Stripping target 'qemu-system-sparc' using strip.
Installing qemu-system-sparc64 to /usr/local/bin
Stripping target 'qemu-system-sparc64' using strip.
Installing qemu-system-tricore to /usr/local/bin
Stripping target 'qemu-system-tricore' using strip.
Installing qemu-system-x86_64 to /usr/local/bin
Stripping target 'qemu-system-x86_64' using strip.
Installing qemu-system-xtensa to /usr/local/bin
Stripping target 'qemu-system-xtensa' using strip.
Installing qemu-system-xtensaeb to /usr/local/bin
Stripping target 'qemu-system-xtensaeb' using strip.
Installing qemu-aarch64 to /usr/local/bin
Stripping target 'qemu-aarch64' using strip.
Installing qemu-aarch64_be to /usr/local/bin
Stripping target 'qemu-aarch64_be' using strip.
Installing qemu-alpha to /usr/local/bin
Stripping target 'qemu-alpha' using strip.
Installing qemu-arm to /usr/local/bin
Stripping target 'qemu-arm' using strip.
Installing qemu-armeb to /usr/local/bin
Stripping target 'qemu-armeb' using strip.
Installing qemu-cris to /usr/local/bin
Stripping target 'qemu-cris' using strip.
Installing qemu-hppa to /usr/local/bin
Stripping target 'qemu-hppa' using strip.
Installing qemu-i386 to /usr/local/bin
Stripping target 'qemu-i386' using strip.
Installing qemu-m68k to /usr/local/bin
Stripping target 'qemu-m68k' using strip.
Installing qemu-microblaze to /usr/local/bin
Stripping target 'qemu-microblaze' using strip.
Installing qemu-microblazeel to /usr/local/bin
Stripping target 'qemu-microblazeel' using strip.
Installing qemu-mips to /usr/local/bin
Stripping target 'qemu-mips' using strip.
Installing qemu-mips64 to /usr/local/bin
Stripping target 'qemu-mips64' using strip.
Installing qemu-mips64el to /usr/local/bin
Stripping target 'qemu-mips64el' using strip.
Installing qemu-mipsel to /usr/local/bin
Stripping target 'qemu-mipsel' using strip.
Installing qemu-mipsn32 to /usr/local/bin
Stripping target 'qemu-mipsn32' using strip.
Installing qemu-mipsn32el to /usr/local/bin
Stripping target 'qemu-mipsn32el' using strip.
Installing qemu-nios2 to /usr/local/bin
Stripping target 'qemu-nios2' using strip.
Installing qemu-or1k to /usr/local/bin
Stripping target 'qemu-or1k' using strip.
Installing qemu-ppc to /usr/local/bin
Stripping target 'qemu-ppc' using strip.
Installing qemu-ppc64 to /usr/local/bin
Stripping target 'qemu-ppc64' using strip.
Installing qemu-ppc64le to /usr/local/bin
Stripping target 'qemu-ppc64le' using strip.
Installing qemu-riscv32 to /usr/local/bin
Stripping target 'qemu-riscv32' using strip.
Installing qemu-riscv64 to /usr/local/bin
Stripping target 'qemu-riscv64' using strip.
Installing qemu-s390x to /usr/local/bin
Stripping target 'qemu-s390x' using strip.
Installing qemu-sh4 to /usr/local/bin
Stripping target 'qemu-sh4' using strip.
Installing qemu-sh4eb to /usr/local/bin
Stripping target 'qemu-sh4eb' using strip.
Installing qemu-sparc to /usr/local/bin
Stripping target 'qemu-sparc' using strip.
Installing qemu-sparc32plus to /usr/local/bin
Stripping target 'qemu-sparc32plus' using strip.
Installing qemu-sparc64 to /usr/local/bin
Stripping target 'qemu-sparc64' using strip.
Installing qemu-x86_64 to /usr/local/bin
Stripping target 'qemu-x86_64' using strip.
Installing qemu-xtensa to /usr/local/bin
Stripping target 'qemu-xtensa' using strip.
Installing qemu-xtensaeb to /usr/local/bin
Stripping target 'qemu-xtensaeb' using strip.
Installing qga/qemu-ga to /usr/local/bin
Stripping target 'qga/qemu-ga' using strip.
Installing qemu-keymap to /usr/local/bin
Stripping target 'qemu-keymap' using strip.
Installing qemu-img to /usr/local/bin
Stripping target 'qemu-img' using strip.
Installing qemu-io to /usr/local/bin
Stripping target 'qemu-io' using strip.
Installing qemu-nbd to /usr/local/bin
Stripping target 'qemu-nbd' using strip.
Installing storage-daemon/qemu-storage-daemon to /usr/local/bin
Stripping target 'storage-daemon/qemu-storage-daemon' using strip.
Installing contrib/elf2dmp/elf2dmp to /usr/local/bin
Stripping target 'contrib/elf2dmp/elf2dmp' using strip.
Installing qemu-edid to /usr/local/bin
Stripping target 'qemu-edid' using strip.
Installing contrib/vhost-user-gpu/vhost-user-gpu to /usr/local/libexec
Stripping target 'contrib/vhost-user-gpu/vhost-user-gpu' using strip.
Installing qemu-bridge-helper to /usr/local/libexec
Stripping target 'qemu-bridge-helper' using strip.
Installing qemu-pr-helper to /usr/local/bin
Stripping target 'qemu-pr-helper' using strip.
Installing pc-bios/edk2-aarch64-code.fd to /usr/local/share/qemu
Installing pc-bios/edk2-arm-code.fd to /usr/local/share/qemu
Installing pc-bios/edk2-arm-vars.fd to /usr/local/share/qemu
Installing pc-bios/edk2-i386-code.fd to /usr/local/share/qemu
Installing pc-bios/edk2-i386-secure-code.fd to /usr/local/share/qemu
Installing pc-bios/edk2-i386-vars.fd to /usr/local/share/qemu
Installing pc-bios/edk2-x86_64-code.fd to /usr/local/share/qemu
Installing pc-bios/edk2-x86_64-secure-code.fd to /usr/local/share/qemu
Installing pc-bios/keymaps/ar to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/bepo to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/cz to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/da to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/de to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/de-ch to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/en-gb to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/en-us to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/es to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/et to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fi to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fo to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fr to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fr-be to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fr-ca to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/fr-ch to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/hr to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/hu to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/is to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/it to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/ja to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/lt to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/lv to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/mk to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/nl to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/no to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/pl to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/pt to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/pt-br to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/ru to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/th to /usr/local/share/qemu/keymaps
Installing pc-bios/keymaps/tr to /usr/local/share/qemu/keymaps
Installing /home/pi/Documents/qemu/ui/icons/qemu_16x16.png to /usr/local/share/icons/hicolor/16x16/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_24x24.png to /usr/local/share/icons/hicolor/24x24/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_32x32.png to /usr/local/share/icons/hicolor/32x32/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_48x48.png to /usr/local/share/icons/hicolor/48x48/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_64x64.png to /usr/local/share/icons/hicolor/64x64/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_128x128.png to /usr/local/share/icons/hicolor/128x128/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_256x256.png to /usr/local/share/icons/hicolor/256x256/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_512x512.png to /usr/local/share/icons/hicolor/512x512/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu_32x32.bmp to /usr/local/share/icons/hicolor/32x32/apps
Installing /home/pi/Documents/qemu/ui/icons/qemu.svg to /usr/local/share/icons/hicolor/scalable/apps
Installing /home/pi/Documents/qemu/ui/qemu.desktop to /usr/local/share/applications
Installing /home/pi/Documents/qemu/build/contrib/vhost-user-gpu/50-qemu-gpu.json to /usr/local/share/qemu/vhost-user
Installing /home/pi/Documents/qemu/pc-bios/bios.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/bios-256k.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/bios-microvm.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/qboot.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/sgabios.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-cirrus.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-stdvga.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-vmware.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-qxl.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-virtio.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-ramfb.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-bochs-display.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/vgabios-ati.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/openbios-sparc32 to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/openbios-sparc64 to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/openbios-ppc to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/QEMU,tcx.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/QEMU,cgthree.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-e1000.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-eepro100.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-ne2k_pci.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-pcnet.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-rtl8139.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pxe-virtio.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-e1000.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-eepro100.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-ne2k_pci.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-pcnet.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-rtl8139.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-virtio.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-e1000e.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/efi-vmxnet3.rom to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/qemu-nsis.bmp to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/bamboo.dtb to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/canyonlands.dtb to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/petalogix-s3adsp1800.dtb to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/petalogix-ml605.dtb to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/multiboot.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/linuxboot.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/linuxboot_dma.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/kvmvapic.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/pvh.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/s390-ccw.img to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/s390-netboot.img to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/slof.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/skiboot.lid to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/palcode-clipper to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/u-boot.e500 to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/u-boot-sam460-20100605.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/qemu_vga.ndrv to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/edk2-licenses.txt to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/hppa-firmware.img to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/opensbi-riscv32-generic-fw_dynamic.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/opensbi-riscv64-generic-fw_dynamic.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/opensbi-riscv32-generic-fw_dynamic.elf to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/opensbi-riscv64-generic-fw_dynamic.elf to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/pc-bios/npcm7xx_bootrom.bin to /usr/local/share/qemu
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/50-edk2-i386-secure.json to /usr/local/share/qemu/firmware
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/50-edk2-x86_64-secure.json to /usr/local/share/qemu/firmware
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/60-edk2-aarch64.json to /usr/local/share/qemu/firmware
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/60-edk2-arm.json to /usr/local/share/qemu/firmware
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/60-edk2-i386.json to /usr/local/share/qemu/firmware
Installing /home/pi/Documents/qemu/build/pc-bios/descriptors/60-edk2-x86_64.json to /usr/local/share/qemu/firmwareTraceback (most recent call last):
  File "/home/pi/.local/bin/meson", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/mesonmain.py", line 228, in main
    return run(sys.argv[1:], launcher)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/mesonmain.py", line 217, in run
    return run_script_command(args[1], args[2:])
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/mesonmain.py", line 165, in run_script_command
    return module.run(script_args)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/scripts/gettext.py", line 120, in run
    do_install(src_sub, bld_sub, dest, options.pkgname, langs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/scripts/gettext.py", line 87, in do_install
    shutil.copystat(srcfile, tempfile)
  File "/usr/lib/python3.7/shutil.py", line 205, in copystat
    follow_symlinks=follow)
FileNotFoundError: [Errno 2] No such file or directory

Installing /home/pi/Documents/qemu/pc-bios/keymaps/sl to /usr/local/share/qemu/keymaps
Installing /home/pi/Documents/qemu/pc-bios/keymaps/sv to /usr/local/share/qemu/keymaps
Running custom install script '/home/pi/.local/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=qemu'
FAILED: meson-install 
/home/pi/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:172: run-ninja] Error 1
make[1]: Leaving directory '/home/pi/Documents/qemu/build'
make: *** [GNUmakefile:11: install] Error 2

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

pi@Twisterpi4-ultra-4gb:~/Documents/qemu $ 
```
I'm on a raspberry pi 4 4gb on the Lates TwisterOS (basically RPiOS) 32bit.

the output above is when using checkinstall from apt, I also built it from source, but running it gave me the same error.

**Comment by giuliomoro** [comment]
no idea really, does it work fine when you do `sudo make install`?

**Comment by Itai-Nelken** [comment]
> no idea really, does it work fine when you do `sudo make install`?

yes

**Comment by Itai-Nelken** [comment]
I compiled then packaged QEMU using checkinstall on a linux x86_64 (amd64) machine and it worked ok, but on my pi (armhf OS, arm64 CPU) it failed to create a deb of QEMU, only thing that worked was creating a checkinstall deb.

**Comment by giuliomoro** [comment]
I seem to remember that `checkinstall` is no longer actively developed. I made this repo here just to publish a fix. There are better tools than this allegedly. `cpack` could be one ....

**Comment by Itai-Nelken** [comment]
thanks, I built the deb manually at the end
